# Generated by Django 3.2.19 on 2023-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_conect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MsgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaging_product', models.CharField(max_length=100)),
                ('recipient_type', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('type_msg', models.CharField(choices=[('interactive', 'Interactive'), ('text', 'Text'), ('reaction', 'Reaction'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('template', 'Template'), ('location', 'Location')], max_length=20)),
                ('audio_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('reaction_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reaction_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('video_provider_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
